### ISSUE TITLE
Error 404 on Fetch APIs

### ISSUE THREAD

**Issue by alankun5** [kayecandy/gcakes-fe#10]
## Description of bug
Related to issue #9, Fetch APIs returning Error 404.
In addition to previous issue #9, errors only occur to localhost. Deployment server is fine.

## Steps to Reproduce
1. Run app on local machine
2. Either visit `localhost:3000/` or `localhost:3000/register`
3. Make a fetch request
4. Enter and check Developer Tools `Console` and `Network` Tabs

## Screenshots
**Register Page Fetch**
![image](https://user-images.githubusercontent.com/104754302/222150447-884644f8-5b30-4a1f-9688-8d7ecdec4b69.png)
![image](https://user-images.githubusercontent.com/104754302/222150634-3fb482f7-09bf-4646-82df-d3516df9eaee.png)

**Cakes Page Fetch**
![image](https://user-images.githubusercontent.com/104754302/222150814-902dea49-3b34-48eb-a6f2-2b55d23d9b98.png)
![image](https://user-images.githubusercontent.com/104754302/222150918-1712242a-101c-4a31-b15f-06cb3902bb43.png)

**Homepage Featured Products**
![image](https://user-images.githubusercontent.com/104754302/222151140-522562a6-7ab9-434e-a084-04046802bd7c.png)
![image](https://user-images.githubusercontent.com/104754302/222151203-e7e0b67b-fc39-4405-8618-f01d7f121b75.png)

**Comment by kayecandy** [comment]
Try verifying your env file? I added some changes awhile back. New version is in google drive
